### ISSUE TITLE
ca not figure out installation

### ISSUE THREAD

**Issue by matesio** [RBech/QuickPay_Magento2#2]
hi   , i am using  magento 2  http://chosting.dk/ but can not figure out how to configure quickpay_magento2   , please give me some concise steps to setup 
thanks

**Comment by RBech** [comment]
Hi Matesio

Sure thing, I'll try...The prerequisites are SSH access and composer (getcomposer.org)

- Connect to your host via SSH
- Navigate to your webroot
- Issue the command "composer require quickpay/magento2"
- Once composer is done downloading issue the following 3 commands
- php bin/magento module:enable QuickPay_Payment
- php bin/magento setup:upgrade
- php bin/magento setup:di:compile

And that should do it :)

**Comment by RBech** [comment]
@matesio since I haven't heard from you again I assume you figured it out, closing the issue for now
